import Head from "next/head";
import Header from "./components/Header/Header";
import ContentContainer from "./components/ContentContainer/ContentContainer";
import styles from "../styles/index.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.layout}>
        <Header />
        <ContentContainer />
      </div>
    </>
  );
}
